# [[rule.device_rule]]
# name = "AT Translated Set 2 keyboard"
# kb_layout = "us"
#
# [[rule.device_rule]]
# name = "A4Tech USB Mouse"
# accel_speed = 0
# natural_scrolling = 0
#
# [[rule.device_rule]]
# type = "trackpad"
# tap_to_click = 1
# natural_scrolling = 0
